image: node:14.21.3

stages:
- build
- test
- deploy

build-job:
  stage: build
  script:
  - npm run build
  artifacts:
    path:
    - dist

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
